version: 2.1

executors:
  ruby-executor:
    docker:
      - image: circleci/ruby:3.2-node  # Ruby dengan Node.js (untuk Rails jika menggunakan Webpacker)
        environment:
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3
      - image: circleci/postgres:13.4-alpine  # Database Postgres
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: test_db
          POSTGRES_PASSWORD: password
    working_directory: ~/project

jobs:
  setup:
    executor: ruby-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            gem install bundler
            bundle install

  test:
    executor: ruby-executor
    steps:
      - checkout
      - run:
          name: Run database setup
          command: |
            bundle exec rails db:create
            bundle exec rails db:migrate
      - run:
          name: Run tests
          command: bundle exec rspec  # Ganti sesuai framework (misal: `rails test`)

workflows:
  version: 2.1
  ruby-workflow:
    jobs:
      - setup
      - test:
          requires:
            - setup
